import type { CalculatorInput } from '@/types/calculator'

// ─────────────────────────────────────────────────────────────────────────
// Input-field schemas for calculators whose forms (in the source platform)
// declare their inputs inside dedicated React components rather than in the
// registry. These were transcribed from those form components so the generic
// renderer can drive every calculator. Also overrides a few registry entries
// that needed richer inputs (sofa vasopressor, tsat units, bmi height, and the
// binary CURB-65 / PERC / STOP-BANG fields). Field `id`s match exactly what
// each calculator's `calculate()` reads.
// ─────────────────────────────────────────────────────────────────────────

export const INPUT_OVERRIDES: Record<string, CalculatorInput[]> = {
  'aih': [
    { id: 'anaSma', label: 'ANA or SMA/F-actin', type: 'radio', required: true, options: [ { value: 0, label: 'Negative (0)' }, { value: 1, label: 'Positive or strongly positive (+1)' } ] },
    { id: 'lkm1', label: 'LKM1 antibody', type: 'radio', required: true, options: [ { value: 0, label: '<1:40 (0)' }, { value: 2, label: '>=1:40 (+2)' } ] },
    { id: 'sla', label: 'SLA', type: 'radio', required: true, options: [ { value: 0, label: 'Negative (0)' }, { value: 2, label: 'Positive (+2)' } ] },
    { id: 'igg', label: 'IgG', type: 'radio', required: true, options: [ { value: 0, label: 'Normal (0)' }, { value: 1, label: '>Upper limit of normal (+1)' }, { value: 2, label: '>1.1x upper limit of normal (+2)' } ] },
    { id: 'histology', label: 'Liver histology', type: 'radio', required: true, options: [ { value: 1, label: 'Compatible with AIH (+1)' }, { value: 2, label: 'Typical of AIH (+2)' } ] },
    { id: 'viralHepatitis', label: 'Viral hepatitis', type: 'radio', required: true, options: [ { value: 0, label: 'Present (0)' }, { value: 2, label: 'Absent (+2)' } ] },
  ],
  'original-aih': [
    { id: 'sex', label: 'Sex', type: 'radio', required: true, options: [ { value: 0, label: 'Male (0)' }, { value: 2, label: 'Female (+2)' } ] },
    { id: 'alpAstAltRatio', label: 'ALP:AST or ALP:ALT ratio', type: 'radio', required: true, options: [ { value: 2, label: '<1.5 (+2)' }, { value: 0, label: '1.5-3.0 (0)' }, { value: -2, label: '>3.0 (-2)' } ] },
    { id: 'serumGlobulinsIgg', label: 'Serum globulins or IgG', type: 'radio', required: true, options: [ { value: 3, label: '>2.0 (+3)' }, { value: 2, label: '1.5-2.0 (+2)' }, { value: 1, label: '1.0-1.5 (+1)' }, { value: 0, label: '<1.0 (0)' } ] },
    { id: 'antibodies', label: 'ANA, SMA, or LKM-1 antibody', type: 'radio', required: true, options: [ { value: 3, label: '>1:80 (+3)' }, { value: 2, label: '1:80 (+2)' }, { value: 1, label: '1:40 (+1)' }, { value: 0, label: '<1:40 (0)' } ] },
    { id: 'optionalAutoantibodies', label: 'Optional additional parameters', type: 'radio', required: true, options: [ { value: 2, label: 'Other defined autoantibodies (+2)' }, { value: 1, label: 'HLA-DR3 or HLA-DR4 (+1)' }, { value: 0, label: 'None of the above (0)' } ] },
    { id: 'ama', label: 'AMA', type: 'radio', required: true, options: [ { value: -4, label: 'Positive (-4)' }, { value: 0, label: 'Negative (0)' } ] },
    { id: 'hepatitisViralMarkers', label: 'Hepatitis viral markers', type: 'radio', required: true, options: [ { value: -3, label: 'Positive (-3)' }, { value: 3, label: 'Negative (+3)' } ] },
    { id: 'hepatotoxicDrugs', label: 'Recent/current hepatotoxic drugs', type: 'radio', required: true, options: [ { value: -4, label: 'Yes (-4)' }, { value: 1, label: 'No (+1)' } ] },
    { id: 'alcoholIntake', label: 'Average alcohol intake', type: 'radio', required: true, options: [ { value: 2, label: '<25 g/day (+2)' }, { value: 0, label: '25-60 g/day (0)' }, { value: -2, label: '>60 g/day (-2)' } ] },
    { id: 'interfaceHepatitis', label: 'Histology: interface hepatitis', type: 'radio', required: true, options: [ { value: 3, label: 'Yes (+3)' }, { value: 0, label: 'No (0)' } ] },
    { id: 'lymphoplasmacytic', label: 'Histology: predominantly lymphoplasmacytic', type: 'radio', required: true, options: [ { value: 1, label: 'Yes (+1)' }, { value: 0, label: 'No (0)' } ] },
    { id: 'rosetting', label: 'Histology: rosetting of liver cells', type: 'radio', required: true, options: [ { value: 1, label: 'Yes (+1)' }, { value: 0, label: 'No (0)' } ] },
    { id: 'biliaryChanges', label: 'Histology: biliary changes', type: 'radio', required: true, options: [ { value: -3, label: 'Yes (-3)' }, { value: 0, label: 'No (0)' } ] },
    { id: 'otherChanges', label: 'Histology: other changes', type: 'radio', required: true, options: [ { value: -3, label: 'Yes (-3)' }, { value: 0, label: 'No (0)' } ] },
    { id: 'autoimmuneDisease', label: 'Other autoimmune disease(s)', type: 'radio', required: true, options: [ { value: 2, label: 'Yes (+2)' }, { value: 0, label: 'No (0)' } ] },
    { id: 'responseTherapy', label: 'Response to therapy', type: 'radio', required: true, options: [ { value: 2, label: 'Complete (+2)' }, { value: 3, label: 'Relapse (+3)' } ] },
  ],
  'cdai': [
    { id: 'tenderJointCount', label: 'Tender joint count', type: 'number', required: true, min: 0 },
    { id: 'swollenJointCount', label: 'Swollen joint count', type: 'number', required: true, min: 0 },
    { id: 'patientGlobal', label: 'Patient global assessment (0-10)', type: 'number', required: true, min: 0, max: 10 },
    { id: 'providerGlobal', label: 'Provider global assessment (0-10)', type: 'number', required: true, min: 0, max: 10 },
  ],
  'sdai': [
    { id: 'tenderJointCount', label: 'Tender joint count', type: 'number', required: true, min: 0 },
    { id: 'swollenJointCount', label: 'Swollen joint count', type: 'number', required: true, min: 0 },
    { id: 'crpMgDl', label: 'C-reactive protein (mg/dL)', type: 'number', required: true, min: 0 },
    { id: 'patientGlobal', label: 'Patient global assessment (0-10)', type: 'number', required: true, min: 0, max: 10 },
    { id: 'providerGlobal', label: 'Provider global assessment (0-10)', type: 'number', required: true, min: 0, max: 10 },
  ],
  'basdai': [
    { id: 'q1', label: '1. Fatigue/tiredness (0-10)', type: 'number', required: true, min: 0, max: 10 },
    { id: 'q2', label: '2. AS neck/back/hip pain (0-10)', type: 'number', required: true, min: 0, max: 10 },
    { id: 'q3', label: '3. Pain/swelling other joints (0-10)', type: 'number', required: true, min: 0, max: 10 },
    { id: 'q4', label: '4. Discomfort from tender areas (0-10)', type: 'number', required: true, min: 0, max: 10 },
    { id: 'q5', label: '5. Morning stiffness severity (0-10)', type: 'number', required: true, min: 0, max: 10 },
    { id: 'q6', label: '6. Morning stiffness duration (0-10)', type: 'number', required: true, min: 0, max: 10 },
  ],
  'sledai': [
    { id: 'seizure', label: 'Recent onset seizure', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 8, label: 'Yes (+8)' } ] },
    { id: 'psychosis', label: 'Psychosis', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 8, label: 'Yes (+8)' } ] },
    { id: 'organicBrainSyndrome', label: 'Organic brain syndrome', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 8, label: 'Yes (+8)' } ] },
    { id: 'visualDisturbance', label: 'Visual disturbance', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 8, label: 'Yes (+8)' } ] },
    { id: 'neuropathy', label: 'Cranial nerve neuropathy', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 8, label: 'Yes (+8)' } ] },
    { id: 'lupusHeadache', label: 'Lupus headache', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 8, label: 'Yes (+8)' } ] },
    { id: 'stroke', label: 'New onset stroke', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 8, label: 'Yes (+8)' } ] },
    { id: 'vasculitis', label: 'Vasculitis', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 8, label: 'Yes (+8)' } ] },
    { id: 'arthritis', label: 'Arthritis', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 4, label: 'Yes (+4)' } ] },
    { id: 'myositis', label: 'Myositis', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 4, label: 'Yes (+4)' } ] },
    { id: 'urinaryCasts', label: 'Heme-granular or RBC casts', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 4, label: 'Yes (+4)' } ] },
    { id: 'hematuria', label: 'Hematuria', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 4, label: 'Yes (+4)' } ] },
    { id: 'proteinuria', label: 'Proteinuria', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 4, label: 'Yes (+4)' } ] },
    { id: 'pyuria', label: 'Pyuria', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 4, label: 'Yes (+4)' } ] },
    { id: 'rash', label: 'Inflammatory-type rash', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 2, label: 'Yes (+2)' } ] },
    { id: 'alopecia', label: 'Alopecia', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 2, label: 'Yes (+2)' } ] },
    { id: 'mucosalUlcers', label: 'Oral/nasal mucosal ulcers', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 2, label: 'Yes (+2)' } ] },
    { id: 'pleuriticPain', label: 'Pleurisy', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 2, label: 'Yes (+2)' } ] },
    { id: 'pericarditis', label: 'Pericarditis', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 2, label: 'Yes (+2)' } ] },
    { id: 'lowComplement', label: 'Low complement', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 2, label: 'Yes (+2)' } ] },
    { id: 'highDnaBinding', label: 'High DNA binding', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 2, label: 'Yes (+2)' } ] },
    { id: 'fever', label: 'Fever >38°C', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'platelets', label: 'Platelets <100 ×10⁹/L', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'wbc', label: 'WBC <3 ×10⁹/L', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
  ],
  'das28-esr': [
    { id: 'tenderJointCount', label: 'Tender joint count', type: 'number', required: true, min: 0 },
    { id: 'swollenJointCount', label: 'Swollen joint count', type: 'number', required: true, min: 0 },
    { id: 'esr', label: 'ESR (mm/hr)', type: 'number', required: true, min: 0 },
    { id: 'globalHealth', label: 'Global health (0-10)', type: 'number', required: true, min: 0, max: 10 },
  ],
  'apri': [
    { id: 'ast', label: 'AST (U/L)', type: 'number', required: true, min: 0 },
    { id: 'astUpperLimit', label: 'AST upper limit of normal (U/L)', type: 'number', required: true, min: 0 },
    { id: 'platelets', label: 'Platelet count', type: 'number', required: true, min: 0 },
    { id: 'plateletUnit', label: 'Platelet unit', type: 'select', required: true, options: [ { value: '10^9/L', label: '×10⁹/L' }, { value: '10^3/uL', label: '×10³/µL' } ] },
  ],
  'fib-4': [
    { id: 'age', label: 'Age (years)', type: 'number', required: true, min: 0 },
    { id: 'ast', label: 'AST (U/L)', type: 'number', required: true, min: 0 },
    { id: 'alt', label: 'ALT (U/L)', type: 'number', required: true, min: 0 },
    { id: 'platelets', label: 'Platelet count', type: 'number', required: true, min: 0 },
    { id: 'plateletUnit', label: 'Platelet unit', type: 'select', required: true, options: [ { value: '10^9/L', label: '×10⁹/L' }, { value: '10^3/uL', label: '×10³/µL' } ] },
  ],
  'wells-pe': [
    { id: 'dvtSigns', label: 'Clinical signs/symptoms of DVT', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 3, label: 'Yes (+3)' } ] },
    { id: 'pe1st', label: 'PE is #1 diagnosis OR equally likely', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 3, label: 'Yes (+3)' } ] },
    { id: 'heartRate', label: 'Heart rate >100', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1.5, label: 'Yes (+1.5)' } ] },
    { id: 'immobilization', label: 'Immobilization ≥3 days OR surgery in past 4 weeks', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1.5, label: 'Yes (+1.5)' } ] },
    { id: 'previousPeDvt', label: 'Previous objectively diagnosed PE/DVT', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1.5, label: 'Yes (+1.5)' } ] },
    { id: 'hemoptysis', label: 'Hemoptysis', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'malignancy', label: 'Malignancy (treated within 6mo or palliative)', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
  ],
  'wells-dvt': [
    { id: 'activeCancer', label: 'Active cancer', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'bedridden', label: 'Bedridden >3 days or major surgery within 12 weeks', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'calfSwelling', label: 'Calf swelling >3 cm vs other leg', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'collateralVeins', label: 'Collateral superficial veins', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'entireLeg', label: 'Entire leg swollen', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'localTenderness', label: 'Localized tenderness along deep veins', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'pittingEdema', label: 'Pitting edema, symptomatic leg', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'paralysis', label: 'Paralysis/paresis/recent immobilization', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'priorDvt', label: 'Previously documented DVT', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'altDiagnosis', label: 'Alternative diagnosis as likely or more likely', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: -2, label: 'Yes (-2)' } ] },
  ],
  'has-bled': [
    { id: 'hypertension', label: 'Hypertension (uncontrolled, >160 systolic)', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'renalDisease', label: 'Renal disease (dialysis, transplant, Cr >2.26)', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'liverDisease', label: 'Liver disease', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'stroke', label: 'Stroke history', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'bleeding', label: 'Prior major bleeding/predisposition', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'labileINR', label: 'Labile INR (TTR <60%)', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'elderly', label: 'Age >65', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'medications', label: 'Medications predisposing to bleeding', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'alcohol', label: 'Alcohol use (≥8 drinks/week)', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
  ],
  'grace': [
    { id: 'age', label: 'Age (years)', type: 'number', required: true, min: 18, max: 110 },
    { id: 'heartRate', label: 'Heart rate (bpm)', type: 'number', required: true, min: 20, max: 300 },
    { id: 'systolicBP', label: 'Systolic BP (mmHg)', type: 'number', required: true, min: 40, max: 300 },
    { id: 'creatinineMgDl', label: 'Creatinine (mg/dL)', type: 'number', required: true, min: 0, max: 17 },
    { id: 'cardiacArrest', label: 'Cardiac arrest at admission', type: 'radio', required: true, options: [ { value: 0, label: 'No' }, { value: 1, label: 'Yes' } ] },
    { id: 'stDeviation', label: 'ST segment deviation on EKG', type: 'radio', required: true, options: [ { value: 0, label: 'No' }, { value: 1, label: 'Yes' } ] },
    { id: 'abnormalEnzymes', label: 'Abnormal cardiac enzymes', type: 'radio', required: true, options: [ { value: 0, label: 'No' }, { value: 1, label: 'Yes' } ] },
    { id: 'killip', label: 'Killip class', type: 'radio', required: true, options: [ { value: 1, label: 'No CHF' }, { value: 2, label: 'Rales and/or JVD' }, { value: 3, label: 'Pulmonary edema' }, { value: 4, label: 'Cardiogenic shock' } ] },
  ],
  'timi-ua-nstemi': [
    { id: 'age65', label: 'Age ≥65', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'cadRiskFactors', label: '≥3 CAD risk factors', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'knownCAD', label: 'Known CAD (stenosis ≥50%)', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'asaUse', label: 'ASA use in past 7 days', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'severeAngina', label: 'Severe angina (≥2 episodes/24h)', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'stChanges', label: 'EKG ST changes ≥0.5mm', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'cardiacMarker', label: 'Positive cardiac marker', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
  ],
  'cha2ds2-vasc': [
    { id: 'age', label: 'Age', type: 'radio', required: true, options: [ { value: 0, label: '<65 (0)' }, { value: 1, label: '65-74 (+1)' }, { value: 2, label: '≥75 (+2)' } ] },
    { id: 'sex', label: 'Sex', type: 'radio', required: true, options: [ { value: 1, label: 'Female (+1)' }, { value: 0, label: 'Male (0)' } ] },
    { id: 'chf', label: 'CHF history', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'hypertension', label: 'Hypertension history', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'stroke', label: 'Stroke/TIA/thromboembolism history', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 2, label: 'Yes (+2)' } ] },
    { id: 'vascular', label: 'Vascular disease history', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'diabetes', label: 'Diabetes history', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
  ],
  'dapt': [
    { id: 'age', label: 'Age', type: 'radio', required: true, options: [ { value: -2, label: '≥75 (-2)' }, { value: -1, label: '65-74 (-1)' }, { value: 0, label: '<65 (0)' } ] },
    { id: 'smoking', label: 'Cigarette smoking', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'diabetes', label: 'Diabetes mellitus', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'miPresentation', label: 'MI at presentation', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'priorPciMi', label: 'Prior PCI or prior MI', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'paclitaxel', label: 'Paclitaxel-eluting stent', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'stentDiam', label: 'Stent diameter <3 mm', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'chfLvef', label: 'CHF or LVEF <30%', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 2, label: 'Yes (+2)' } ] },
    { id: 'veinGraft', label: 'Vein graft stent', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 2, label: 'Yes (+2)' } ] },
  ],
  'qtc': [
    { id: 'formula', label: 'Formula', type: 'select', required: true, options: [ { value: 'bazett', label: 'Bazett' }, { value: 'fridericia', label: 'Fridericia' }, { value: 'framingham', label: 'Framingham' }, { value: 'hodges', label: 'Hodges' }, { value: 'rautaharju', label: 'Rautaharju' } ] },
    { id: 'heartRate', label: 'Heart rate (bpm)', type: 'number', required: true, min: 20, max: 300 },
    { id: 'qtMs', label: 'QT interval (ms)', type: 'number', required: true, min: 0, max: 800 },
  ],
  'cardiac-output': [
    { id: 'weightKg', label: 'Weight (kg)', type: 'number', required: true, min: 1, max: 300 },
    { id: 'heightCm', label: 'Height (cm)', type: 'number', required: true, min: 50, max: 250 },
    { id: 'sao2Pct', label: 'SaO₂ (%)', type: 'number', required: true, min: 50, max: 100 },
    { id: 'svo2Pct', label: 'SvO₂ (%)', type: 'number', required: true, min: 20, max: 95 },
    { id: 'hbGdl', label: 'Hemoglobin (g/dL)', type: 'number', required: true, min: 1, max: 25 },
    { id: 'heartRate', label: 'Heart rate (bpm)', type: 'number', required: true, min: 20, max: 300 },
    { id: 'age70plus', label: 'Age', type: 'radio', required: true, options: [ { value: 0, label: '<70 years' }, { value: 1, label: '≥70 years' } ] },
  ],
  'nihss': [
    { id: 'loc', label: '1A: Level of consciousness', type: 'radio', required: true, options: [ { value: 0, label: 'Alert; keenly responsive (0)' }, { value: 1, label: 'Arouses to minor stimulation (+1)' }, { value: 2, label: 'Requires repeated stimulation (+2)' }, { value: 3, label: 'Postures or unresponsive (+3)' } ] },
    { id: 'locQ', label: '1B: Ask month and age', type: 'radio', required: true, options: [ { value: 0, label: 'Both right (0)' }, { value: 1, label: '1 right (+1)' }, { value: 2, label: '0 right (+2)' } ] },
    { id: 'locC', label: "1C: 'Blink eyes' & 'squeeze hands'", type: 'radio', required: true, options: [ { value: 0, label: 'Both tasks (0)' }, { value: 1, label: '1 task (+1)' }, { value: 2, label: '0 tasks (+2)' } ] },
    { id: 'gaze', label: '2: Horizontal gaze', type: 'radio', required: true, options: [ { value: 0, label: 'Normal (0)' }, { value: 1, label: 'Partial gaze palsy (+1)' }, { value: 2, label: 'Forced gaze palsy (+2)' } ] },
    { id: 'visual', label: '3: Visual fields', type: 'radio', required: true, options: [ { value: 0, label: 'No visual loss (0)' }, { value: 1, label: 'Partial hemianopia (+1)' }, { value: 2, label: 'Complete hemianopia (+2)' }, { value: 3, label: 'Bilateral blind/hemianopia (+3)' } ] },
    { id: 'facial', label: '4: Facial palsy', type: 'radio', required: true, options: [ { value: 0, label: 'Normal (0)' }, { value: 1, label: 'Minor (+1)' }, { value: 2, label: 'Partial (+2)' }, { value: 3, label: 'Complete (+3)' } ] },
    { id: 'leftArm', label: '5A: Left arm motor', type: 'radio', required: true, options: [ { value: 0, label: 'No drift (0)' }, { value: 1, label: "Drift, doesn't hit bed (+1)" }, { value: 2, label: 'Some effort vs gravity (+2)' }, { value: 3, label: 'No effort vs gravity (+3)' }, { value: 4, label: 'No movement (+4)' } ] },
    { id: 'rightArm', label: '5B: Right arm motor', type: 'radio', required: true, options: [ { value: 0, label: 'No drift (0)' }, { value: 1, label: "Drift, doesn't hit bed (+1)" }, { value: 2, label: 'Some effort vs gravity (+2)' }, { value: 3, label: 'No effort vs gravity (+3)' }, { value: 4, label: 'No movement (+4)' } ] },
    { id: 'leftLeg', label: '6A: Left leg motor', type: 'radio', required: true, options: [ { value: 0, label: 'No drift (0)' }, { value: 1, label: "Drift, doesn't hit bed (+1)" }, { value: 2, label: 'Some effort vs gravity (+2)' }, { value: 3, label: 'No effort vs gravity (+3)' }, { value: 4, label: 'No movement (+4)' } ] },
    { id: 'rightLeg', label: '6B: Right leg motor', type: 'radio', required: true, options: [ { value: 0, label: 'No drift (0)' }, { value: 1, label: "Drift, doesn't hit bed (+1)" }, { value: 2, label: 'Some effort vs gravity (+2)' }, { value: 3, label: 'No effort vs gravity (+3)' }, { value: 4, label: 'No movement (+4)' } ] },
    { id: 'ataxia', label: '7: Limb ataxia', type: 'radio', required: true, options: [ { value: 0, label: 'No ataxia (0)' }, { value: 1, label: 'Ataxia in 1 limb (+1)' }, { value: 2, label: 'Ataxia in 2 limbs (+2)' } ] },
    { id: 'sensation', label: '8: Sensation', type: 'radio', required: true, options: [ { value: 0, label: 'Normal (0)' }, { value: 1, label: 'Mild-moderate loss (+1)' }, { value: 2, label: 'Complete loss (+2)' } ] },
    { id: 'language', label: '9: Language/aphasia', type: 'radio', required: true, options: [ { value: 0, label: 'No aphasia (0)' }, { value: 1, label: 'Mild-moderate aphasia (+1)' }, { value: 2, label: 'Severe aphasia (+2)' }, { value: 3, label: 'Mute/global aphasia (+3)' } ] },
    { id: 'dysarthria', label: '10: Dysarthria', type: 'radio', required: true, options: [ { value: 0, label: 'Normal (0)' }, { value: 1, label: 'Mild-moderate (+1)' }, { value: 2, label: 'Severe/mute (+2)' } ] },
    { id: 'extinction', label: '11: Extinction/inattention', type: 'radio', required: true, options: [ { value: 0, label: 'No abnormality (0)' }, { value: 1, label: 'Mild inattention (+1)' }, { value: 2, label: 'Profound hemi-inattention (+2)' } ] },
  ],
  'aspects': [
    { id: 'caudate', label: 'Caudate (C)', type: 'radio', required: true, options: [ { value: 0, label: 'Normal (0)' }, { value: -1, label: 'Affected (-1)' } ] },
    { id: 'internalCapsule', label: 'Internal Capsule (IC)', type: 'radio', required: true, options: [ { value: 0, label: 'Normal (0)' }, { value: -1, label: 'Affected (-1)' } ] },
    { id: 'lentiform', label: 'Lentiform nucleus (L)', type: 'radio', required: true, options: [ { value: 0, label: 'Normal (0)' }, { value: -1, label: 'Affected (-1)' } ] },
    { id: 'insularRibbon', label: 'Insular Ribbon (I)', type: 'radio', required: true, options: [ { value: 0, label: 'Normal (0)' }, { value: -1, label: 'Affected (-1)' } ] },
    { id: 'm1', label: 'Anterior MCA cortex (M1)', type: 'radio', required: true, options: [ { value: 0, label: 'Normal (0)' }, { value: -1, label: 'Affected (-1)' } ] },
    { id: 'm2', label: 'MCA cortex lateral to insula (M2)', type: 'radio', required: true, options: [ { value: 0, label: 'Normal (0)' }, { value: -1, label: 'Affected (-1)' } ] },
    { id: 'm3', label: 'Posterior MCA cortex (M3)', type: 'radio', required: true, options: [ { value: 0, label: 'Normal (0)' }, { value: -1, label: 'Affected (-1)' } ] },
    { id: 'm4', label: 'Anterior cortex rostral to M1 (M4)', type: 'radio', required: true, options: [ { value: 0, label: 'Normal (0)' }, { value: -1, label: 'Affected (-1)' } ] },
    { id: 'm5', label: 'Lateral cortex rostral to M3 (M5)', type: 'radio', required: true, options: [ { value: 0, label: 'Normal (0)' }, { value: -1, label: 'Affected (-1)' } ] },
    { id: 'm6', label: 'Posterior cortex rostral to M3 (M6)', type: 'radio', required: true, options: [ { value: 0, label: 'Normal (0)' }, { value: -1, label: 'Affected (-1)' } ] },
  ],
  'edss': [
    { id: 'ambulation', label: 'Ambulation', type: 'select', required: true, options: [ { value: 0, label: 'Fully ambulatory (0)' }, { value: 4, label: 'Walk ≥500m without aid (4)' }, { value: 4.5, label: 'Walk ≥300m without aid (4.5)' }, { value: 5, label: 'Walk ≥200m without aid (5)' }, { value: 5.5, label: 'Walk ≥100m without aid (5.5)' }, { value: 6, label: 'Unilateral aid to walk 100m (6)' }, { value: 6.5, label: 'Bilateral aid to walk 20m (6.5)' }, { value: 7, label: 'Wheelchair, transfers alone (7)' }, { value: 7.5, label: 'Wheelchair, needs aid (7.5)' }, { value: 8, label: 'Restricted to bed/chair (8)' }, { value: 8.5, label: 'Restricted to bed much of day (8.5)' }, { value: 9, label: 'Helpless bed patient (9)' }, { value: 9.5, label: 'Totally helpless (9.5)' }, { value: 10, label: 'Death due to MS (10)' } ] },
    { id: 'pyramidal', label: 'Pyramidal FS', type: 'select', required: true, options: [ { value: 0, label: 'Normal (0)' }, { value: 1, label: 'Signs only (+1)' }, { value: 2, label: 'Minimal disability (+2)' }, { value: 3, label: 'Mild/moderate paraparesis (+3)' }, { value: 4, label: 'Marked paraparesis (+4)' }, { value: 5, label: 'Paraplegia (+5)' }, { value: 6, label: 'Quadriplegia (+6)' } ] },
    { id: 'cerebellar', label: 'Cerebellar FS', type: 'select', required: true, options: [ { value: 0, label: 'Normal (0)' }, { value: 1, label: 'Signs only (+1)' }, { value: 2, label: 'Mild ataxia (+2)' }, { value: 3, label: 'Moderate ataxia (+3)' }, { value: 4, label: 'Severe ataxia, all limbs (+4)' }, { value: 5, label: 'Unable to coordinate (+5)' } ] },
    { id: 'brainstem', label: 'Brainstem FS', type: 'select', required: true, options: [ { value: 0, label: 'Normal (0)' }, { value: 1, label: 'Signs only (+1)' }, { value: 2, label: 'Moderate nystagmus (+2)' }, { value: 3, label: 'Severe nystagmus (+3)' }, { value: 4, label: 'Marked dysarthria (+4)' }, { value: 5, label: 'Unable to swallow/speak (+5)' } ] },
    { id: 'sensory', label: 'Sensory FS', type: 'select', required: true, options: [ { value: 0, label: 'Normal (0)' }, { value: 1, label: 'Vibration decrease 1-2 limbs (+1)' }, { value: 2, label: 'Mild decrease touch/pain (+2)' }, { value: 3, label: 'Moderate decrease (+3)' }, { value: 4, label: 'Marked decrease (+4)' }, { value: 5, label: 'Loss in 1-2 limbs (+5)' }, { value: 6, label: 'Sensation lost below head (+6)' } ] },
    { id: 'bowelBladder', label: 'Bowel & bladder FS', type: 'select', required: true, options: [ { value: 0, label: 'Normal (0)' }, { value: 1, label: 'Mild hesitancy/urgency (+1)' }, { value: 2, label: 'Moderate; rare incontinence (+2)' }, { value: 3, label: 'Frequent incontinence (+3)' }, { value: 4, label: 'Almost constant catheterization (+4)' }, { value: 5, label: 'Loss of bladder function (+5)' }, { value: 6, label: 'Loss of bowel & bladder (+6)' } ] },
    { id: 'visual', label: 'Visual FS', type: 'select', required: true, options: [ { value: 0, label: 'Normal (0)' }, { value: 1, label: 'Scotoma, acuity >20/30 (+1)' }, { value: 2, label: 'Acuity 20/30-20/59 (+2)' }, { value: 3, label: 'Acuity 20/60-20/99 (+3)' }, { value: 4, label: 'Acuity 20/100-20/200 (+4)' }, { value: 5, label: 'Acuity <20/200 (+5)' }, { value: 6, label: 'Grade 5 + better eye ≤20/60 (+6)' } ] },
    { id: 'cerebral', label: 'Cerebral FS', type: 'select', required: true, options: [ { value: 0, label: 'Normal (0)' }, { value: 1, label: 'Mood alteration only (+1)' }, { value: 2, label: 'Mild decrease mentation (+2)' }, { value: 3, label: 'Moderate decrease (+3)' }, { value: 4, label: 'Marked decrease (+4)' }, { value: 5, label: 'Dementia/severe (+5)' } ] },
    { id: 'other', label: 'Other FS', type: 'radio', required: true, options: [ { value: 0, label: 'None (0)' }, { value: 1, label: 'Other MS findings (+1)' } ] },
  ],
  'abcd2': [
    { id: 'age60', label: 'Age ≥60 years', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'bp', label: 'BP ≥140/90 mmHg', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'clinical', label: 'Clinical features', type: 'radio', required: true, options: [ { value: 2, label: 'Unilateral weakness (+2)' }, { value: 1, label: 'Speech disturbance, no weakness (+1)' }, { value: 0, label: 'Other symptoms (0)' } ] },
    { id: 'duration', label: 'Symptom duration', type: 'radio', required: true, options: [ { value: 0, label: '<10 min (0)' }, { value: 1, label: '10-59 min (+1)' }, { value: 2, label: '≥60 min (+2)' } ] },
    { id: 'diabetes', label: 'History of diabetes', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
  ],
  'ich': [
    { id: 'gcs', label: 'Glasgow Coma Score', type: 'radio', required: true, options: [ { value: 2, label: '3-4 (+2)' }, { value: 1, label: '5-12 (+1)' }, { value: 0, label: '13-15 (0)' } ] },
    { id: 'age80', label: 'Age ≥80', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'ichVolume', label: 'ICH volume ≥30 mL', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'ivh', label: 'Intraventricular hemorrhage', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'infratentorial', label: 'Infratentorial origin', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
  ],
  'mrs': [
    { id: 'score', label: 'Baseline activity', type: 'radio', required: true, options: [ { value: 0, label: 'No symptoms (0)' }, { value: 1, label: 'No significant disability (1)' }, { value: 2, label: 'Slight disability (2)' }, { value: 3, label: 'Moderate disability (3)' }, { value: 4, label: 'Moderately severe (4)' }, { value: 5, label: 'Severe disability (5)' }, { value: 6, label: 'Dead (6)' } ] },
  ],
  'hunt-hess': [
    { id: 'grade', label: 'Signs/symptoms', type: 'radio', required: true, options: [ { value: 1, label: 'I — Mild HA, minimal rigidity (1)' }, { value: 2, label: 'II — Severe HA, nuchal rigidity, no deficit (2)' }, { value: 3, label: 'III — Lethargy/confusion, mild deficit (3)' }, { value: 4, label: 'IV — Stupor, severe deficit (4)' }, { value: 5, label: 'V — Coma, posturing (5)' } ] },
  ],
  'news': [
    { id: 'respiratory', label: 'Respiratory rate', type: 'radio', required: true, options: [ { value: 3, label: '≤8 (+3)' }, { value: 1, label: '9-11 (+1)' }, { value: 0, label: '12-20 (0)' }, { value: 2, label: '21-24 (+2)' }, { value: 3, label: '≥25 (+3)' } ] },
    { id: 'spo2', label: 'Oxygen saturation', type: 'radio', required: true, options: [ { value: 3, label: '≤91% (+3)' }, { value: 2, label: '92-93% (+2)' }, { value: 1, label: '94-95% (+1)' }, { value: 0, label: '≥96% (0)' } ] },
    { id: 'supplementalO2', label: 'Supplemental oxygen', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 2, label: 'Yes (+2)' } ] },
    { id: 'temperature', label: 'Temperature', type: 'radio', required: true, options: [ { value: 3, label: '≤35.0°C (+3)' }, { value: 1, label: '35.1-36.0°C (+1)' }, { value: 0, label: '36.1-38.0°C (0)' }, { value: 1, label: '38.1-39.0°C (+1)' }, { value: 2, label: '≥39.1°C (+2)' } ] },
    { id: 'systolicBP', label: 'Systolic BP', type: 'radio', required: true, options: [ { value: 3, label: '≤90 (+3)' }, { value: 2, label: '91-100 (+2)' }, { value: 1, label: '101-110 (+1)' }, { value: 0, label: '111-219 (0)' }, { value: 3, label: '≥220 (+3)' } ] },
    { id: 'heartRate', label: 'Heart rate', type: 'radio', required: true, options: [ { value: 3, label: '≤40 (+3)' }, { value: 1, label: '41-50 (+1)' }, { value: 0, label: '51-90 (0)' }, { value: 1, label: '91-110 (+1)' }, { value: 2, label: '111-130 (+2)' }, { value: 3, label: '≥131 (+3)' } ] },
    { id: 'consciousness', label: 'Consciousness (AVPU)', type: 'radio', required: true, options: [ { value: 0, label: 'Alert (0)' }, { value: 3, label: 'V, P or U (+3)' } ] },
  ],
  'gcs': [
    { id: 'eye', label: 'Best eye response', type: 'select', required: true, options: [ { value: 4, label: 'Spontaneously (4)' }, { value: 3, label: 'To verbal command (3)' }, { value: 2, label: 'To pain (2)' }, { value: 1, label: 'No eye opening (1)' }, { value: 'NT', label: 'Not testable' } ] },
    { id: 'verbal', label: 'Best verbal response', type: 'select', required: true, options: [ { value: 5, label: 'Oriented (5)' }, { value: 4, label: 'Confused (4)' }, { value: 3, label: 'Inappropriate words (3)' }, { value: 2, label: 'Incomprehensible sounds (2)' }, { value: 1, label: 'No verbal response (1)' }, { value: 'NT', label: 'Not testable/intubated' } ] },
    { id: 'motor', label: 'Best motor response', type: 'select', required: true, options: [ { value: 6, label: 'Obeys commands (6)' }, { value: 5, label: 'Localizes pain (5)' }, { value: 4, label: 'Withdrawal from pain (4)' }, { value: 3, label: 'Flexion to pain (3)' }, { value: 2, label: 'Extension to pain (2)' }, { value: 1, label: 'No motor response (1)' }, { value: 'NT', label: 'Not testable' } ] },
  ],
  'sofa-2': [
    { id: 'brain', label: 'Brain (GCS)', type: 'radio', required: true, options: [ { value: 0, label: '15 (0)' }, { value: 1, label: '13-14 / localizing (+1)' }, { value: 2, label: '9-12 / withdrawal (+2)' }, { value: 3, label: '6-8 / flexion (+3)' }, { value: 4, label: '3-5 / extension (+4)' } ] },
    { id: 'respiratory', label: 'Respiratory (PaO₂:FiO₂)', type: 'radio', required: true, options: [ { value: 0, label: '>300 (0)' }, { value: 1, label: '≤300 (+1)' }, { value: 2, label: '≤225 (+2)' }, { value: 3, label: '≤150 + ventilation (+3)' }, { value: 4, label: '≤75 + ventilation/ECMO (+4)' } ] },
    { id: 'cardiovascular', label: 'Cardiovascular', type: 'radio', required: true, options: [ { value: 0, label: 'MAP ≥70, no pressors (0)' }, { value: 1, label: 'MAP <70, no pressors (+1)' }, { value: 2, label: 'Low-dose vasopressor (+2)' }, { value: 3, label: 'Medium-dose vasopressor (+3)' }, { value: 4, label: 'High-dose vasopressor (+4)' } ] },
    { id: 'liver', label: 'Liver (bilirubin)', type: 'radio', required: true, options: [ { value: 0, label: '≤1.2 mg/dL (0)' }, { value: 1, label: '≤3.0 mg/dL (+1)' }, { value: 2, label: '≤6.0 mg/dL (+2)' }, { value: 3, label: '≤12.0 mg/dL (+3)' }, { value: 4, label: '>12 mg/dL (+4)' } ] },
    { id: 'kidney', label: 'Kidney (creatinine)', type: 'radio', required: true, options: [ { value: 0, label: '≤1.2 mg/dL (0)' }, { value: 1, label: '≤2.0 mg/dL or low UO 6-12h (+1)' }, { value: 2, label: '≤3.5 mg/dL or low UO ≥12h (+2)' }, { value: 3, label: '>3.5 mg/dL or anuria (+3)' }, { value: 4, label: 'RRT (+4)' } ] },
    { id: 'hemostasis', label: 'Hemostasis (platelets)', type: 'radio', required: true, options: [ { value: 0, label: '>150 ×10³/µL (0)' }, { value: 1, label: '≤150 (+1)' }, { value: 2, label: '≤100 (+2)' }, { value: 3, label: '≤80 (+3)' }, { value: 4, label: '≤50 (+4)' } ] },
  ],
  'frax': [
    { id: 'age', label: 'Age (years)', type: 'radio', required: true, options: [ { value: 0, label: '<65 (0)' }, { value: 1, label: '65-69 (+1)' }, { value: 2, label: '70-74 (+2)' }, { value: 3, label: '75-79 (+3)' }, { value: 4, label: '80-84 (+4)' }, { value: 5, label: '≥85 (+5)' } ] },
    { id: 'fractureHistory', label: 'Fracture after age 50', type: 'radio', required: true, options: [ { value: 0, label: "No/don't know (0)" }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'motherHipFracture', label: "Mother's hip fracture after 50", type: 'radio', required: true, options: [ { value: 0, label: "No/don't know (0)" }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'weight', label: 'Weight', type: 'radio', required: true, options: [ { value: 0, label: '>125 lb / >56.7 kg (0)' }, { value: 1, label: '≤125 lb / ≤56.7 kg (+1)' } ] },
    { id: 'smoker', label: 'Current smoker', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'chairRise', label: 'Uses arms to stand from chair', type: 'radio', required: true, options: [ { value: 0, label: "No/don't know (0)" }, { value: 2, label: 'Yes (+2)' } ] },
    { id: 'bmd', label: 'Total hip T-score (optional)', type: 'radio', required: false, options: [ { value: 0, label: '≥-1 (0)' }, { value: 2, label: '-1 to -2 (+2)' }, { value: 3, label: '-2 to -2.5 (+3)' }, { value: 4, label: '<-2.5 (+4)' } ] },
  ],
  'cci': [
    { id: 'prePlt', label: 'Pre-transfusion platelets (×10⁹/L)', type: 'number', required: true, min: 0, max: 1000 },
    { id: 'postPlt', label: 'Post-transfusion platelets (×10⁹/L)', type: 'number', required: true, min: 0, max: 1000 },
    { id: 'timeHour', label: 'Time after transfusion', type: 'radio', required: true, options: [ { value: 1, label: '1-hour' }, { value: 20, label: '20-hour' } ] },
    { id: 'heightCm', label: 'Height (cm)', type: 'number', required: true, min: 0, max: 250 },
    { id: 'weightKg', label: 'Weight (kg)', type: 'number', required: true, min: 0, max: 300 },
    { id: 'unitContent', label: 'Platelet unit content (×10¹¹)', type: 'number', required: true, min: 0, max: 20 },
  ],
  'blood-volume': [
    { id: 'patientType', label: 'Patient', type: 'select', required: true, options: [ { value: 'preterm', label: 'Preterm neonate' }, { value: 'term', label: 'Term neonate' }, { value: 'infant', label: 'Infant 1-4 months' }, { value: 'child', label: 'Child <25 kg' }, { value: 'adult', label: 'Child ≥25 kg or adult' } ] },
    { id: 'sex', label: 'Sex', type: 'select', required: false, options: [ { value: 'male', label: 'Male' }, { value: 'female', label: 'Female' } ], dependsOn: { field: 'patientType', value: 'adult' } },
    { id: 'heightCm', label: 'Height (cm)', type: 'number', required: false, min: 0, max: 250, dependsOn: { field: 'patientType', value: 'adult' } },
    { id: 'weightKg', label: 'Weight (kg)', type: 'number', required: true, min: 0, max: 300 },
    { id: 'hematocrit', label: 'Hematocrit (%)', type: 'number', required: false, min: 0, max: 70 },
  ],
  'ipss-r': [
    { id: 'cytogenetics', label: 'Cytogenetic group', type: 'radio', required: true, options: [ { value: 0, label: 'Very good (0)' }, { value: 1, label: 'Good (+1)' }, { value: 2, label: 'Intermediate (+2)' }, { value: 3, label: 'Poor (+3)' }, { value: 4, label: 'Very poor (+4)' } ] },
    { id: 'blasts', label: 'Marrow blasts (%)', type: 'radio', required: true, options: [ { value: 0, label: '≤2 (0)' }, { value: 1, label: '>2 to <5 (+1)' }, { value: 2, label: '5-10 (+2)' }, { value: 3, label: '>10 (+3)' } ] },
    { id: 'hemoglobin', label: 'Hemoglobin (g/dL)', type: 'radio', required: true, options: [ { value: 0, label: '≥10 (0)' }, { value: 1, label: '8 to <10 (+1)' }, { value: 1.5, label: '<8 (+1.5)' } ] },
    { id: 'platelets', label: 'Platelets (×10⁹/L)', type: 'radio', required: true, options: [ { value: 0, label: '≥100 (0)' }, { value: 0.5, label: '50 to <100 (+0.5)' }, { value: 1, label: '<50 (+1)' } ] },
    { id: 'anc', label: 'ANC (×10⁹/L)', type: 'radio', required: true, options: [ { value: 0, label: '≥0.8 (0)' }, { value: 0.5, label: '<0.8 (+0.5)' } ] },
  ],
  'ipss': [
    { id: 'karyotype', label: 'Karyotype', type: 'radio', required: true, options: [ { value: 0, label: 'Good (0)' }, { value: 0.5, label: 'Intermediate (+0.5)' }, { value: 1, label: 'Poor (+1)' } ] },
    { id: 'blasts', label: 'Marrow blasts (%)', type: 'radio', required: true, options: [ { value: 0, label: '<5% (0)' }, { value: 0.5, label: '5-10% (+0.5)' }, { value: 1.5, label: '11-20% (+1.5)' }, { value: 2, label: '21-30% (+2)' } ] },
    { id: 'cytopenias', label: 'Number of cytopenias', type: 'radio', required: true, options: [ { value: 0, label: '0-1 (0)' }, { value: 0.5, label: '2-3 (+0.5)' } ] },
  ],
  'flipi': [
    { id: 'age60', label: 'Age >60 years', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'nodalSites', label: '>4 nodal sites', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'ldh', label: 'LDH elevated', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'hemoglobin', label: 'Hemoglobin <12 g/dL', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'stageIIIIV', label: 'Stage III-IV', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
  ],
  'cll-ipi': [
    { id: 'age', label: 'Age', type: 'radio', required: true, options: [ { value: 0, label: '≤65 years (0)' }, { value: 1, label: '>65 years (+1)' } ] },
    { id: 'clinicalStage', label: 'Clinical stage', type: 'radio', required: true, options: [ { value: 0, label: 'Binet A / Rai 0 (0)' }, { value: 1, label: 'Binet B-C / Rai I-IV (+1)' } ] },
    { id: 'b2m', label: 'β2 microglobulin (mg/L)', type: 'radio', required: true, options: [ { value: 0, label: '≤3.5 (0)' }, { value: 2, label: '>3.5 (+2)' } ] },
    { id: 'ighv', label: 'IGHV mutational status', type: 'radio', required: true, options: [ { value: 0, label: 'Mutated (0)' }, { value: 2, label: 'Unmutated (+2)' } ] },
    { id: 'tp53', label: 'TP53 status', type: 'radio', required: true, options: [ { value: 0, label: 'No abnormalities (0)' }, { value: 4, label: 'del(17p) and/or TP53 mutation (+4)' } ] },
  ],
  // Registry overrides (richer than the registry's bare numeric fields)
  'sofa': [
    { id: 'pao2', label: 'PaO₂ (mmHg)', type: 'number', required: false, min: 20, max: 600 },
    { id: 'fio2', label: 'FiO₂ (0.21-1.0)', type: 'number', required: false, min: 0.21, max: 1.0 },
    { id: 'spo2', label: 'SpO₂ (%)', type: 'number', required: false, min: 50, max: 100 },
    { id: 'ventilated', label: 'Mechanically ventilated', type: 'toggle', required: false },
    { id: 'platelets', label: 'Platelets (×10³/µL)', type: 'number', required: true, min: 0, max: 1000 },
    { id: 'bilirubin', label: 'Total Bilirubin', type: 'number', required: true, units: ['mg/dL', 'µmol/L'], defaultUnit: 'mg/dL', substance: 'bilirubin' },
    { id: 'map', label: 'Mean arterial pressure (mmHg)', type: 'number', required: true, min: 20, max: 200 },
    { id: 'vasopressor', label: 'Vasopressor agent', type: 'select', required: false, options: [ { value: '', label: 'None' }, { value: 'dopamine', label: 'Dopamine' }, { value: 'dobutamine', label: 'Dobutamine' }, { value: 'epinephrine', label: 'Epinephrine' }, { value: 'norepinephrine', label: 'Norepinephrine' } ] },
    { id: 'vasopressorDose', label: 'Vasopressor dose (µg/kg/min)', type: 'number', required: false, min: 0 },
    { id: 'gcs', label: 'GCS (3-15)', type: 'number', required: true, min: 3, max: 15 },
    { id: 'creatinine', label: 'Serum Creatinine', type: 'number', required: true, units: ['mg/dL', 'µmol/L'], defaultUnit: 'mg/dL', substance: 'creatinine' },
    { id: 'urineOutput', label: 'Urine output (mL/24h)', type: 'number', required: false, min: 0, max: 10000 },
  ],
  'tsat': [
    { id: 'serumIron', label: 'Serum Iron', type: 'number', required: true, units: ['µg/dL', 'µmol/L'], defaultUnit: 'µg/dL', min: 0, substance: 'iron' },
    { id: 'tibcMethod', label: 'Binding capacity method', type: 'radio', required: true, options: [ { value: 'tibc', label: 'TIBC' }, { value: 'transferrin', label: 'Transferrin' } ] },
    { id: 'tibcValue', label: 'TIBC / Transferrin value', type: 'number', required: true, units: ['µg/dL', 'µmol/L', 'g/dL', 'g/L'], defaultUnit: 'µg/dL', min: 0, substance: 'iron' },
    { id: 'ferritin', label: 'Serum Ferritin (ng/mL, optional)', type: 'number', required: false, min: 0 },
  ],
  'bmi': [
    { id: 'weight', label: 'Weight', type: 'number', required: true, units: ['kg', 'lb'], defaultUnit: 'kg', min: 1, max: 500 },
    { id: 'heightUnit', label: 'Height unit', type: 'select', required: true, options: [ { value: 'cm', label: 'cm' }, { value: 'm', label: 'm' }, { value: 'ft+in', label: 'ft + in' } ] },
    { id: 'height', label: 'Height', type: 'number', required: false, min: 1 },
    { id: 'heightFeet', label: 'Height (feet)', type: 'number', required: false, min: 0, max: 8, dependsOn: { field: 'heightUnit', value: 'ft+in' } },
    { id: 'heightInches', label: 'Height (inches)', type: 'number', required: false, min: 0, max: 11, dependsOn: { field: 'heightUnit', value: 'ft+in' } },
    { id: 'sex', label: 'Biological sex (for IBW)', type: 'radio', required: false, options: [ { value: 'male', label: 'Male' }, { value: 'female', label: 'Female' } ] },
  ],
  'curb65': [
    { id: 'confusion', label: 'Confusion', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'bun', label: 'BUN >19 mg/dL', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'rr', label: 'Respiratory rate ≥30', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'bp', label: 'SBP <90 or DBP ≤60', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'age65', label: 'Age ≥65', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
  ],
  'perc': [
    { id: 'age50', label: 'Age ≥50', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'hr100', label: 'Heart rate ≥100', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'o2sat', label: 'O₂ sat <95%', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'legSwelling', label: 'Unilateral leg swelling', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'hemoptysis', label: 'Hemoptysis', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'surgery', label: 'Recent surgery/trauma', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'priorPeDvt', label: 'Prior PE or DVT', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'hormones', label: 'Hormone use', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
  ],
  'stop-bang': [
    { id: 'snore', label: 'Snore loudly', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'tired', label: 'Daytime tiredness', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'observed', label: 'Observed apnea', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'pressure', label: 'High blood pressure', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'bmi', label: 'BMI >35', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'age', label: 'Age >50', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'neck', label: 'Neck >40 cm', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
    { id: 'gender', label: 'Male gender', type: 'radio', required: true, options: [ { value: 0, label: 'No (0)' }, { value: 1, label: 'Yes (+1)' } ] },
  ],
}
